### ISSUE TITLE
Unexpected input(s) 'error-message', valid inputs are ['entryPoint', 'args', 'title-regex']

### ISSUE THREAD

**Issue by sammcj** [seferov/pr-lint-action#235]
Providing `error-message` as an input to this action causes an error/warning:

```
Unexpected input(s) 'error-message', valid inputs are ['entryPoint', 'args', 'title-regex']
```

Configuration:

```yaml
  lint:
    runs-on: ubuntu-22.04
    env:
      PR_TITLE: ${{inputs.pr_title}}
    steps:
      - uses: seferov/pr-lint-action@master
        with:
          title-regex: '(^(IF|KLUE|KIS)-[0-9]+|^Hotfix-([0-9]+(\/[0-9]+)+))\s--\s[^\n\r]+$'
          error-message: 'Expected format:\n(IF|KLUE|KIS)-<Jira Ticket> || Hotfix-2022/03/09 -- short description'
```
